### ISSUE TITLE
What happened to this repo?

### ISSUE THREAD

**Issue by Shamil-Xero** [iamwatchdogs/Infytq-Programming-Fundamentals-using-Python-Part-2#1]
Basically, I was searching for the answers for "Infosys Programming Fundamentals using Python" and found this wonder repo. I am currently studying CSE 2nd year and I even though don't believe in certifications, my college if forcing us to do this every month. So, when I came to this repo (The previous part 1) I was so happy that I could spend my time in other projects. Your GitHub profile is amazing, and I really liked how well you show cased the answer for the Infosys course. So, I would like to get the answers for part 2 also.

**Comment by iamwatchdogs** [comment]
Hi @Shamil-Xero, It's nice to meet you.

Thank you all the compliments and it really make me happy that you find my repos helpful. I worked on these repo as i need to complete the certification for InfyTQ platform as per my college placement program. Unfortunately, this repo was left unfinished as my college decided to move on from this certifications as they're no longer part of the college placement program.

I've tried to solve, gather all the solution to complete this repo, but I couldn't find enough time during my college days. I'm so sorry to tell you that, this repo will not be maintained anymore... And maybe even deleted in the upcoming days.

I'm really sorry to disappoint you, but I can no longer work on this. Hope you understand.
